In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [14]:
b = np.array([(1,5,6), (3,8,4)])
print(b)

[[1 5 6]
 [3 8 4]]


In [15]:
b.max() #maior numero da matriz

8

In [16]:
b.min() #menor numero da matriz

1

In [17]:
b.sum() #soma da matriz

27

In [18]:
b.mean() #média da matriz

4.5

In [19]:
b.std() #desvio padrão

2.217355782608345

In [9]:
c = np.zeros((4,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
c = np.ones((4,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
c = np.eye(10)
print(c)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
